-- MySQL Script generated by MySQL Workbench
-- Mon Apr 11 14:40:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nodejs_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nodejs_db` ;

-- -----------------------------------------------------
-- Schema nodejs_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nodejs_db` DEFAULT CHARACTER SET utf8 ;
USE `nodejs_db` ;

-- -----------------------------------------------------
-- Table `nodejs_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nodejs_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) );


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
